# Generated by Django 5.1.1 on 2024-10-18 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='O nome deve conter apenas letras', regex='^[a-zá-ùA-ZÁ-Ù]+((?:[\\s][a-zá-ùA-ZÁ-Ù]+)?)+$')], verbose_name='name'),
        ),
    ]
