# Generated by Django 5.1.1 on 2024-10-19 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantidade')),
                ('price', models.DecimalField(
                    decimal_places=2, max_digits=7, verbose_name='preço')),
                ('cart', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('product', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Oder_Item',
                'verbose_name_plural': 'Order_Items',
            },
        ),
    ]
