# Generated by Django 5.1.1 on 2024-10-20 00:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payment_method', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='O nome deve conter apenas letras e números', regex='^[a-zá-ùA-ZÁ-Ù0-9]+((?:[\\s][a-zá-ùA-ZÁ-Ù0-9]+)?)+$')])),
                ('city', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='O nome deve conter apenas letras e números', regex='^[a-zá-ùA-ZÁ-Ù0-9]+((?:[\\s][a-zá-ùA-ZÁ-Ù0-9]+)?)+$')])),
                ('state', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='O nome deve conter apenas letras e números', regex='^[a-zá-ùA-ZÁ-Ù0-9]+((?:[\\s][a-zá-ùA-ZÁ-Ù0-9]+)?)+$')])),
                ('number', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="O nome deve conter apenas letras números e o serparador '-'", regex='^[a-zA-Z0-9-]+((?:[a-zA-Z0-9-]+)?)+$')])),
                ('neighborhood', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='O nome deve conter apenas letras e números', regex='^[a-zá-ùA-ZÁ-Ù0-9]+((?:[\\s][a-zá-ùA-ZÁ-Ù0-9]+)?)+$')])),
                ('complement', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='O nome deve conter apenas letras e números', regex='^[a-zá-ùA-ZÁ-Ù0-9]+((?:[\\s][a-zá-ùA-ZÁ-Ù0-9]+)?)+$')])),
                ('reference_point', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='O nome deve conter apenas letras e números', regex='^[a-zá-ùA-ZÁ-Ù0-9]+((?:[\\s][a-zá-ùA-ZÁ-Ù0-9]+)?)+$')])),
                ('zip_code', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='O CEP deve conter 8 números', regex='^[0-9]{8}$')])),
                ('status', models.CharField(choices=[('A', 'Em Aberto'), ('F', 'Fechada')], max_length=9)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'purchase',
                'verbose_name_plural': 'purchases',
            },
        ),
    ]
