# Generated by Django 5.1.1 on 2024-10-18 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='O nome deve conter apenas letras', regex='^[a-zá-ùA-ZÁ-Ù]+((?:[\\s][a-zá-ùA-ZÁ-Ù]+)?)+$')], verbose_name='Nome')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preco')),
                ('available_quantity', models.IntegerField(verbose_name='Quantidade disponível')),
                ('description', models.TextField(max_length=150, verbose_name='Descrição')),
                ('brand', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='O nome deve conter apenas letras e números', regex='^[a-zá-ùA-ZÁ-Ù0-9]+((?:[\\s][a-zá-ùA-ZÁ-Ù0-9]+)?)+$')], verbose_name='Marca')),
                ('maker', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='O nome deve conter apenas letras e números', regex='^[a-zá-ùA-ZÁ-Ù0-9]+((?:[\\s][a-zá-ùA-ZÁ-Ù0-9]+)?)+$')], verbose_name='Fabricante')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso')),
                ('ean', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='O codigo de barras(EAN) deve conter 13 números', regex='^([0-9]{13})$')], verbose_name='Código de barras')),
                ('sku', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='O codigo SKU deve conter 13 caracteres(números, Letras maiusculas e traço(-))', regex='^([0-9-A-Z]{13})$')], verbose_name='SKU')),
                ('image', models.ImageField(upload_to='Imagem_Produto/%Y/%m')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
