# Generated by Django 5.1.1 on 2024-10-18 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_address_city_alter_address_complement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='O nome deve conter apenas letras e números', regex='^[a-zá-ùA-ZÁ-Ù0-9]+((?:[\\s][a-zá-ùA-ZÁ-Ù0-9]+)?)+$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='O nome deve conter apenas letras e números', regex='^[a-zá-ùA-ZÁ-Ù0-9]+((?:[\\s][a-zá-ùA-ZÁ-Ù0-9]+)?)+$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='O nome deve conter apenas letras e números', regex='^[a-zá-ùA-ZÁ-Ù0-9]+((?:[\\s][a-zá-ùA-ZÁ-Ù0-9]+)?)+$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="O nome deve conter apenas letras números e o serparador '-'", regex='^[a-zA-Z0-9-]+((?:[a-zA-Z0-9-]+)?)+$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='reference_point',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='O nome deve conter apenas letras e números', regex='^[a-zá-ùA-ZÁ-Ù0-9]+((?:[\\s][a-zá-ùA-ZÁ-Ù0-9]+)?)+$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='O nome deve conter apenas letras e números', regex='^[a-zá-ùA-ZÁ-Ù0-9]+((?:[\\s][a-zá-ùA-ZÁ-Ù0-9]+)?)+$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='O nome deve conter apenas letras e números', regex='^[a-zá-ùA-ZÁ-Ù0-9]+((?:[\\s][a-zá-ùA-ZÁ-Ù0-9]+)?)+$')]),
        ),
    ]
